// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/hermes/v1/api_send_email.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailRequest struct {
	Email                *Email   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b383b39b4755d24, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetEmail() *Email {
	if m != nil {
		return m.Email
	}
	return nil
}

type SendEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b383b39b4755d24, []int{1}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendEmailRequest)(nil), "alpacalabs.hermes.v1.SendEmailRequest")
	proto.RegisterType((*SendEmailResponse)(nil), "alpacalabs.hermes.v1.SendEmailResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/hermes/v1/api_send_email.proto", fileDescriptor_2b383b39b4755d24)
}

var fileDescriptor_2b383b39b4755d24 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0xcc, 0x29, 0x48,
	0x4c, 0x4e, 0xcc, 0x49, 0x4c, 0x2a, 0xd6, 0xcf, 0x48, 0x2d, 0xca, 0x4d, 0x2d, 0xd6, 0x2f, 0x33,
	0xd4, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x4e, 0xcd, 0x4b, 0x89, 0x4f, 0xcd, 0x4d, 0xcc, 0xcc, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x41, 0x28, 0xd5, 0x83, 0x28, 0xd5, 0x2b, 0x33, 0x94,
	0x52, 0xc0, 0x6a, 0x00, 0x92, 0x3e, 0x25, 0x57, 0x2e, 0x81, 0xe0, 0xd4, 0xbc, 0x14, 0x57, 0x90,
	0x50, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x21, 0x17, 0x2b, 0x58, 0x89, 0x04, 0xa3,
	0x02, 0xa3, 0x06, 0xb7, 0x91, 0xb4, 0x1e, 0x36, 0xb3, 0xf5, 0x20, 0x5a, 0x20, 0x2a, 0x95, 0x84,
	0xb9, 0x04, 0x91, 0x8c, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x35, 0x2a, 0x42, 0x32, 0x3b, 0x38,
	0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x28, 0x8e, 0x8b, 0x13, 0x2e, 0x26, 0xa4, 0x86, 0xdd, 0x64,
	0x74, 0x07, 0x49, 0xa9, 0x13, 0x54, 0x07, 0xb1, 0x51, 0x89, 0xc1, 0x69, 0x2e, 0x23, 0x97, 0x44,
	0x72, 0x7e, 0x2e, 0x56, 0x0d, 0x4e, 0xdc, 0x1e, 0x60, 0x66, 0x00, 0xc8, 0xe7, 0x01, 0x8c, 0x51,
	0x76, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x8e, 0x60, 0xf5, 0x3e,
	0xa0, 0x80, 0x02, 0x07, 0x4c, 0x51, 0x6a, 0x41, 0xbe, 0x2e, 0x44, 0xa7, 0x6e, 0x7a, 0xbe, 0x3e,
	0xb6, 0x70, 0x5c, 0xc4, 0xc4, 0xec, 0xe8, 0xe3, 0xb1, 0x8a, 0x49, 0x04, 0xa1, 0x57, 0x0f, 0x62,
	0x81, 0x5e, 0x98, 0xe1, 0x29, 0x64, 0xe1, 0x18, 0x88, 0x70, 0x4c, 0x98, 0x61, 0x12, 0x1b, 0xd8,
	0x74, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xc3, 0xd1, 0xf4, 0xdb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendEmailServiceClient is the client API for SendEmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendEmailServiceClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type sendEmailServiceClient struct {
	cc *grpc.ClientConn
}

func NewSendEmailServiceClient(cc *grpc.ClientConn) SendEmailServiceClient {
	return &sendEmailServiceClient{cc}
}

func (c *sendEmailServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/alpacalabs.hermes.v1.SendEmailService/SendEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendEmailServiceServer is the server API for SendEmailService service.
type SendEmailServiceServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
}

func RegisterSendEmailServiceServer(s *grpc.Server, srv SendEmailServiceServer) {
	s.RegisterService(&_SendEmailService_serviceDesc, srv)
}

func _SendEmailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendEmailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alpacalabs.hermes.v1.SendEmailService/SendEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendEmailServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendEmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alpacalabs.hermes.v1.SendEmailService",
	HandlerType: (*SendEmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _SendEmailService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alpacalabs/hermes/v1/api_send_email.proto",
}
