// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/hermes/v1/api_send_sms.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendSmsRequest struct {
	To                   string   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSmsRequest) Reset()         { *m = SendSmsRequest{} }
func (m *SendSmsRequest) String() string { return proto.CompactTextString(m) }
func (*SendSmsRequest) ProtoMessage()    {}
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9745ceb04b6c9d75, []int{0}
}

func (m *SendSmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSmsRequest.Unmarshal(m, b)
}
func (m *SendSmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSmsRequest.Marshal(b, m, deterministic)
}
func (m *SendSmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSmsRequest.Merge(m, src)
}
func (m *SendSmsRequest) XXX_Size() int {
	return xxx_messageInfo_SendSmsRequest.Size(m)
}
func (m *SendSmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSmsRequest proto.InternalMessageInfo

func (m *SendSmsRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SendSmsRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendSmsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSmsResponse) Reset()         { *m = SendSmsResponse{} }
func (m *SendSmsResponse) String() string { return proto.CompactTextString(m) }
func (*SendSmsResponse) ProtoMessage()    {}
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9745ceb04b6c9d75, []int{1}
}

func (m *SendSmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSmsResponse.Unmarshal(m, b)
}
func (m *SendSmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSmsResponse.Marshal(b, m, deterministic)
}
func (m *SendSmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSmsResponse.Merge(m, src)
}
func (m *SendSmsResponse) XXX_Size() int {
	return xxx_messageInfo_SendSmsResponse.Size(m)
}
func (m *SendSmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendSmsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SendSmsRequest)(nil), "alpacalabs.hermes.v1.SendSmsRequest")
	proto.RegisterType((*SendSmsResponse)(nil), "alpacalabs.hermes.v1.SendSmsResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/hermes/v1/api_send_sms.proto", fileDescriptor_9745ceb04b6c9d75)
}

var fileDescriptor_9745ceb04b6c9d75 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xcc, 0x29, 0x48,
	0x4c, 0x4e, 0xcc, 0x49, 0x4c, 0x2a, 0xd6, 0xcf, 0x48, 0x2d, 0xca, 0x4d, 0x2d, 0xd6, 0x2f, 0x33,
	0xd4, 0x4f, 0x2c, 0xc8, 0x8c, 0x2f, 0x4e, 0xcd, 0x4b, 0x89, 0x2f, 0xce, 0x2d, 0xd6, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x41, 0x28, 0xd4, 0x83, 0x28, 0xd4, 0x2b, 0x33, 0x54, 0xb2, 0xe2,
	0xe2, 0x0b, 0x4e, 0xcd, 0x4b, 0x09, 0xce, 0x2d, 0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0xe2, 0xe3, 0x62, 0x2a, 0xc9, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x2a, 0xc9, 0x17,
	0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x02, 0x0b, 0xc2, 0xb8,
	0x4a, 0x82, 0x5c, 0xfc, 0x70, 0xbd, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x46, 0x59, 0x70, 0xe3,
	0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x22, 0xb8, 0xd8, 0xa1, 0x22, 0x42, 0x2a, 0x7a,
	0xd8, 0x9c, 0xa0, 0x87, 0x6a, 0xbf, 0x94, 0x2a, 0x01, 0x55, 0x10, 0x9b, 0x94, 0x18, 0x9c, 0xe6,
	0x32, 0x72, 0x49, 0x24, 0xe7, 0xe7, 0x62, 0x55, 0xee, 0xc4, 0xed, 0x01, 0x66, 0x06, 0x80, 0xbc,
	0x1e, 0xc0, 0x18, 0x65, 0x97, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0xef,
	0x08, 0x56, 0xef, 0x03, 0x0a, 0x30, 0x70, 0xc8, 0x14, 0xa5, 0x16, 0xe4, 0xeb, 0x42, 0x74, 0xea,
	0xa6, 0xe7, 0xeb, 0x63, 0x0b, 0xcf, 0x45, 0x4c, 0xcc, 0x8e, 0x3e, 0x1e, 0xab, 0x98, 0x44, 0x10,
	0x7a, 0xf5, 0x20, 0x16, 0xe8, 0x85, 0x19, 0x9e, 0x42, 0x16, 0x8e, 0x81, 0x08, 0xc7, 0x84, 0x19,
	0x26, 0xb1, 0x81, 0x4d, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x04, 0x3f, 0x9f, 0xc6, 0xa2,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendSmsServiceClient is the client API for SendSmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendSmsServiceClient interface {
	SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error)
}

type sendSmsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSendSmsServiceClient(cc *grpc.ClientConn) SendSmsServiceClient {
	return &sendSmsServiceClient{cc}
}

func (c *sendSmsServiceClient) SendSms(ctx context.Context, in *SendSmsRequest, opts ...grpc.CallOption) (*SendSmsResponse, error) {
	out := new(SendSmsResponse)
	err := c.cc.Invoke(ctx, "/alpacalabs.hermes.v1.SendSmsService/SendSms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendSmsServiceServer is the server API for SendSmsService service.
type SendSmsServiceServer interface {
	SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error)
}

func RegisterSendSmsServiceServer(s *grpc.Server, srv SendSmsServiceServer) {
	s.RegisterService(&_SendSmsService_serviceDesc, srv)
}

func _SendSmsService_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendSmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendSmsServiceServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/alpacalabs.hermes.v1.SendSmsService/SendSms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendSmsServiceServer).SendSms(ctx, req.(*SendSmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendSmsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "alpacalabs.hermes.v1.SendSmsService",
	HandlerType: (*SendSmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendSms",
			Handler:    _SendSmsService_SendSms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "alpacalabs/hermes/v1/api_send_sms.proto",
}
