// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/hermes/v1/email.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Recipient struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recipient) Reset()         { *m = Recipient{} }
func (m *Recipient) String() string { return proto.CompactTextString(m) }
func (*Recipient) ProtoMessage()    {}
func (*Recipient) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{0}
}

func (m *Recipient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipient.Unmarshal(m, b)
}
func (m *Recipient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipient.Marshal(b, m, deterministic)
}
func (m *Recipient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipient.Merge(m, src)
}
func (m *Recipient) XXX_Size() int {
	return xxx_messageInfo_Recipient.Size(m)
}
func (m *Recipient) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipient.DiscardUnknown(m)
}

var xxx_messageInfo_Recipient proto.InternalMessageInfo

func (m *Recipient) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Recipient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Entry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{1}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EntryList struct {
	List                 []*Entry `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryList) Reset()         { *m = EntryList{} }
func (m *EntryList) String() string { return proto.CompactTextString(m) }
func (*EntryList) ProtoMessage()    {}
func (*EntryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{2}
}

func (m *EntryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryList.Unmarshal(m, b)
}
func (m *EntryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryList.Marshal(b, m, deterministic)
}
func (m *EntryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryList.Merge(m, src)
}
func (m *EntryList) XXX_Size() int {
	return xxx_messageInfo_EntryList.Size(m)
}
func (m *EntryList) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryList.DiscardUnknown(m)
}

var xxx_messageInfo_EntryList proto.InternalMessageInfo

func (m *EntryList) GetList() []*Entry {
	if m != nil {
		return m.List
	}
	return nil
}

type Table struct {
	Data                 []*EntryList `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Columns              *Columns     `protobuf:"bytes,2,opt,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{3}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetData() []*EntryList {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Table) GetColumns() *Columns {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Columns struct {
	CustomWidth          map[string]string `protobuf:"bytes,1,rep,name=custom_width,json=customWidth,proto3" json:"custom_width,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomAlignment      map[string]string `protobuf:"bytes,2,rep,name=custom_alignment,json=customAlignment,proto3" json:"custom_alignment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Columns) Reset()         { *m = Columns{} }
func (m *Columns) String() string { return proto.CompactTextString(m) }
func (*Columns) ProtoMessage()    {}
func (*Columns) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{4}
}

func (m *Columns) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Columns.Unmarshal(m, b)
}
func (m *Columns) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Columns.Marshal(b, m, deterministic)
}
func (m *Columns) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Columns.Merge(m, src)
}
func (m *Columns) XXX_Size() int {
	return xxx_messageInfo_Columns.Size(m)
}
func (m *Columns) XXX_DiscardUnknown() {
	xxx_messageInfo_Columns.DiscardUnknown(m)
}

var xxx_messageInfo_Columns proto.InternalMessageInfo

func (m *Columns) GetCustomWidth() map[string]string {
	if m != nil {
		return m.CustomWidth
	}
	return nil
}

func (m *Columns) GetCustomAlignment() map[string]string {
	if m != nil {
		return m.CustomAlignment
	}
	return nil
}

type Action struct {
	Instructions         string   `protobuf:"bytes,1,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Button               *Button  `protobuf:"bytes,2,opt,name=button,proto3" json:"button,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{5}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetInstructions() string {
	if m != nil {
		return m.Instructions
	}
	return ""
}

func (m *Action) GetButton() *Button {
	if m != nil {
		return m.Button
	}
	return nil
}

type Button struct {
	Color                string   `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	TextColor            string   `protobuf:"bytes,2,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Link                 string   `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}
func (*Button) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{6}
}

func (m *Button) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Button.Unmarshal(m, b)
}
func (m *Button) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Button.Marshal(b, m, deterministic)
}
func (m *Button) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Button.Merge(m, src)
}
func (m *Button) XXX_Size() int {
	return xxx_messageInfo_Button.Size(m)
}
func (m *Button) XXX_DiscardUnknown() {
	xxx_messageInfo_Button.DiscardUnknown(m)
}

var xxx_messageInfo_Button proto.InternalMessageInfo

func (m *Button) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Button) GetTextColor() string {
	if m != nil {
		return m.TextColor
	}
	return ""
}

func (m *Button) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Button) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

type Body struct {
	// Name of the contacted person
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Intro sentences, first displayed in the email
	Intros []string `protobuf:"bytes,2,rep,name=intros,proto3" json:"intros,omitempty"`
	// A list of key+value (useful for displaying parameters/settings/personal info)
	Dictionary []*Entry `protobuf:"bytes,3,rep,name=dictionary,proto3" json:"dictionary,omitempty"`
	// Table is an table where you can put data (pricing grid, a bill, and so on)
	Table *Table `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	// Actions are a list of actions that the user will be able to execute via a button click
	Actions []*Action `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	// Outro sentences, last displayed in the email
	Outros []string `protobuf:"bytes,6,rep,name=outros,proto3" json:"outros,omitempty"`
	// Greeting for the contacted person (default to 'Hi')
	Greeting string `protobuf:"bytes,7,opt,name=greeting,proto3" json:"greeting,omitempty"`
	// Signature for the contacted person (default to 'Yours truly')
	Signature string `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	// Title replaces the greeting+name when set
	Title string `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	// Free markdown content that replaces all content other than header and footer
	Markdown             string   `protobuf:"bytes,10,opt,name=markdown,proto3" json:"markdown,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{7}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Body) GetIntros() []string {
	if m != nil {
		return m.Intros
	}
	return nil
}

func (m *Body) GetDictionary() []*Entry {
	if m != nil {
		return m.Dictionary
	}
	return nil
}

func (m *Body) GetTable() *Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *Body) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Body) GetOutros() []string {
	if m != nil {
		return m.Outros
	}
	return nil
}

func (m *Body) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *Body) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Body) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Body) GetMarkdown() string {
	if m != nil {
		return m.Markdown
	}
	return ""
}

type Email struct {
	Subject              string       `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 *Body        `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	To                   []*Recipient `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc                   []*Recipient `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []*Recipient `protobuf:"bytes,5,rep,name=bcc,proto3" json:"bcc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_d89c8592a29ec2bc, []int{8}
}

func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (m *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(m, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Email) GetTo() []*Recipient {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Email) GetCc() []*Recipient {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *Email) GetBcc() []*Recipient {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func init() {
	proto.RegisterType((*Recipient)(nil), "alpacalabs.hermes.v1.Recipient")
	proto.RegisterType((*Entry)(nil), "alpacalabs.hermes.v1.Entry")
	proto.RegisterType((*EntryList)(nil), "alpacalabs.hermes.v1.EntryList")
	proto.RegisterType((*Table)(nil), "alpacalabs.hermes.v1.Table")
	proto.RegisterType((*Columns)(nil), "alpacalabs.hermes.v1.Columns")
	proto.RegisterMapType((map[string]string)(nil), "alpacalabs.hermes.v1.Columns.CustomAlignmentEntry")
	proto.RegisterMapType((map[string]string)(nil), "alpacalabs.hermes.v1.Columns.CustomWidthEntry")
	proto.RegisterType((*Action)(nil), "alpacalabs.hermes.v1.Action")
	proto.RegisterType((*Button)(nil), "alpacalabs.hermes.v1.Button")
	proto.RegisterType((*Body)(nil), "alpacalabs.hermes.v1.Body")
	proto.RegisterType((*Email)(nil), "alpacalabs.hermes.v1.Email")
}

func init() { proto.RegisterFile("alpacalabs/hermes/v1/email.proto", fileDescriptor_d89c8592a29ec2bc) }

var fileDescriptor_d89c8592a29ec2bc = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcf, 0x6a, 0xdb, 0x4e,
	0x10, 0x46, 0xb2, 0x6c, 0xc7, 0xe3, 0xc0, 0x2f, 0x2c, 0xe6, 0x87, 0x70, 0x13, 0x1a, 0x74, 0xca,
	0x25, 0x12, 0x4e, 0xfa, 0x8f, 0xb6, 0x04, 0xec, 0x10, 0xc8, 0x21, 0x87, 0x54, 0x94, 0x14, 0x4a,
	0x4a, 0x58, 0xad, 0x17, 0x67, 0x1b, 0x49, 0x6b, 0xa4, 0x55, 0x52, 0x3f, 0x4c, 0x2f, 0x3d, 0xf6,
	0x25, 0x7a, 0xef, 0x43, 0xf4, 0xd8, 0xe7, 0x28, 0x3b, 0xbb, 0xb2, 0x93, 0x62, 0x27, 0xe9, 0x6d,
	0xbf, 0xcf, 0xdf, 0x37, 0x3b, 0x9a, 0x99, 0x1d, 0xc3, 0x36, 0x4d, 0xa7, 0x94, 0xd1, 0x94, 0x26,
	0x65, 0x74, 0xc9, 0x8b, 0x8c, 0x97, 0xd1, 0xf5, 0x20, 0xe2, 0x19, 0x15, 0x69, 0x38, 0x2d, 0xa4,
	0x92, 0xa4, 0xb7, 0x50, 0x84, 0x46, 0x11, 0x5e, 0x0f, 0x82, 0xe7, 0xd0, 0x89, 0x39, 0x13, 0x53,
	0xc1, 0x73, 0x45, 0x7a, 0xd0, 0x44, 0x87, 0xef, 0x6c, 0x3b, 0x3b, 0x9d, 0xd8, 0x00, 0x42, 0xc0,
	0xcb, 0x69, 0xc6, 0x7d, 0x17, 0x49, 0x3c, 0x07, 0x11, 0x34, 0x8f, 0x72, 0x55, 0xcc, 0xc8, 0x06,
	0x34, 0xae, 0xf8, 0xcc, 0x1a, 0xf4, 0x51, 0x07, 0xb9, 0xa6, 0x69, 0x55, 0xeb, 0x0d, 0x08, 0xde,
	0x42, 0x07, 0x0d, 0x27, 0xa2, 0x54, 0x24, 0x02, 0x2f, 0x15, 0xa5, 0xf2, 0x9d, 0xed, 0xc6, 0x4e,
	0x77, 0xef, 0x49, 0xb8, 0x2c, 0xb3, 0x10, 0xe5, 0x31, 0x0a, 0x83, 0x0a, 0x9a, 0xef, 0x69, 0x92,
	0x72, 0xb2, 0x0f, 0xde, 0x98, 0x2a, 0x6a, 0x9d, 0x4f, 0xef, 0x71, 0xea, 0x8b, 0x62, 0x14, 0x93,
	0x97, 0xd0, 0x66, 0x32, 0xad, 0xb2, 0xbc, 0xc4, 0x9c, 0xba, 0x7b, 0x5b, 0xcb, 0x7d, 0x87, 0x46,
	0x14, 0xd7, 0xea, 0xe0, 0x87, 0x0b, 0x6d, 0x4b, 0x92, 0x77, 0xb0, 0xce, 0xaa, 0x52, 0xc9, 0xec,
	0xe2, 0x46, 0x8c, 0xd5, 0xa5, 0xcd, 0x20, 0xbc, 0x37, 0x52, 0x78, 0x88, 0x8e, 0x0f, 0xda, 0x60,
	0x3e, 0xa7, 0xcb, 0x16, 0x0c, 0xf9, 0x04, 0x1b, 0x36, 0x24, 0x4d, 0xc5, 0x24, 0xcf, 0x78, 0xae,
	0x7c, 0x17, 0xc3, 0xee, 0x3d, 0x26, 0xec, 0xb0, 0x36, 0x99, 0xd0, 0xff, 0xb1, 0xbb, 0x6c, 0xff,
	0x00, 0x36, 0xfe, 0xbe, 0xff, 0xb1, 0xed, 0x7a, 0xed, 0xbe, 0x72, 0xfa, 0x23, 0xe8, 0x2d, 0xbb,
	0xe8, 0x5f, 0x62, 0x04, 0x09, 0xb4, 0x86, 0x4c, 0x09, 0x99, 0x93, 0x00, 0xd6, 0x45, 0x5e, 0xaa,
	0xa2, 0x42, 0x58, 0x5a, 0xfb, 0x1d, 0x8e, 0x3c, 0x83, 0x56, 0x52, 0x29, 0x25, 0x73, 0xdb, 0xa7,
	0xcd, 0xe5, 0x65, 0x18, 0xa1, 0x26, 0xb6, 0xda, 0x80, 0x43, 0xcb, 0x30, 0x3a, 0x0f, 0x26, 0x53,
	0x59, 0xd4, 0xf3, 0x8b, 0x80, 0x6c, 0x01, 0x28, 0xfe, 0x45, 0x5d, 0x98, 0x9f, 0x4c, 0x8a, 0x1d,
	0xcd, 0x1c, 0xe2, 0xcf, 0x04, 0x3c, 0x0d, 0xfc, 0x86, 0x19, 0x6f, 0x7d, 0xd6, 0x5c, 0x2a, 0xf2,
	0x2b, 0xdf, 0x33, 0x9c, 0x3e, 0x07, 0xbf, 0x5c, 0xf0, 0x46, 0x72, 0x3c, 0x9b, 0xbf, 0x07, 0x67,
	0xf1, 0x1e, 0xc8, 0xff, 0xd0, 0x12, 0xb9, 0x2a, 0x64, 0x89, 0x0d, 0xec, 0xc4, 0x16, 0x91, 0x37,
	0x00, 0x63, 0x81, 0x5f, 0x47, 0x8b, 0x99, 0xdf, 0x78, 0x78, 0xde, 0x6f, 0xc9, 0xc9, 0x00, 0x9a,
	0x4a, 0x4f, 0x3d, 0xa6, 0xb1, 0xd2, 0x87, 0x0f, 0x23, 0x36, 0x4a, 0xf2, 0x02, 0xda, 0xd4, 0x16,
	0xb8, 0x89, 0x97, 0xad, 0x28, 0xa1, 0x69, 0x4a, 0x5c, 0x8b, 0x75, 0xfe, 0xb2, 0xc2, 0xfc, 0x5b,
	0x26, 0x7f, 0x83, 0x48, 0x1f, 0xd6, 0x26, 0x05, 0xe7, 0x4a, 0xe4, 0x13, 0xbf, 0x8d, 0xdf, 0x3b,
	0xc7, 0x64, 0x13, 0x3a, 0xa5, 0x98, 0xe4, 0x54, 0x55, 0x05, 0xf7, 0xd7, 0x4c, 0x59, 0xe7, 0x84,
	0xee, 0x85, 0x12, 0x2a, 0xe5, 0x7e, 0xc7, 0xf4, 0x02, 0x81, 0x8e, 0x97, 0xd1, 0xe2, 0x6a, 0x2c,
	0x6f, 0x72, 0x1f, 0x4c, 0xbc, 0x1a, 0x07, 0xbf, 0x1d, 0x68, 0x1e, 0xe1, 0xc6, 0xf1, 0xa1, 0x5d,
	0x56, 0xc9, 0x67, 0xce, 0x94, 0x2d, 0x72, 0x0d, 0x49, 0x08, 0x5e, 0x22, 0xc7, 0x33, 0x3b, 0x1f,
	0xfd, 0x15, 0xf3, 0x21, 0xc7, 0xb3, 0x18, 0x75, 0x24, 0x02, 0x57, 0x49, 0x5b, 0xf7, 0x15, 0xdb,
	0x62, 0xbe, 0xfe, 0x62, 0x57, 0x49, 0x6d, 0x60, 0xcc, 0xf7, 0x1e, 0x69, 0x60, 0x8c, 0x0c, 0xa0,
	0x91, 0x30, 0x66, 0xab, 0xfd, 0xa0, 0x43, 0x6b, 0x47, 0x5f, 0x1d, 0xf0, 0x99, 0xcc, 0x96, 0x6a,
	0x47, 0xdd, 0x63, 0x3c, 0x9e, 0xea, 0x9d, 0x7d, 0xea, 0x7c, 0x3c, 0x98, 0x08, 0x75, 0x59, 0x25,
	0x21, 0x93, 0x59, 0x34, 0x44, 0xfd, 0x89, 0x5e, 0xf1, 0xb8, 0xd2, 0x0b, 0x3e, 0x95, 0xbb, 0xc6,
	0xb9, 0x3b, 0x91, 0xd1, 0xb2, 0x7f, 0x80, 0x6f, 0x6e, 0x63, 0x78, 0x72, 0xfc, 0xdd, 0xed, 0x2d,
	0xbc, 0xa1, 0xb9, 0x20, 0x3c, 0x1b, 0xfc, 0xbc, 0x4d, 0x9f, 0x1b, 0xfa, 0xfc, 0x6c, 0x90, 0xb4,
	0x30, 0xfa, 0xfe, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x4f, 0x32, 0xf2, 0x54, 0x06, 0x00,
	0x00,
}
